accounts:
  - name: cristina
    coins: ["20000token", "200000000stake"]
  - name: davide
    coins: ["10000token", "100000000stake"]
validator:
  name: cristina
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: davide
  coins: ["5token", "100000stake"]
